name: 'Save docker image to dockerhub'

on:
  # pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      job-name:
        description: 'Name of the job to activate'
        required: true
        default: 'SaveToDockerHub'
        type: choice
        options:
        - SaveToDockerHub

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  SaveToDockerHub:
    name: 'Save docker image to dockerhub'
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    if: github.ref == 'refs/heads/master' || github.event.inputs.job-name == 'SaveToDockerHub' || github.event_name == 'pull_request'
    
    steps:

    - name: Checkout the repo
      uses: actions/checkout@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_TRIBDEVOPS_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TRIBDEVOPS_PAT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: texastribune/walls:latest, texastribune/walls:${{ github.run_number }}
        cache-from: type=registry,ref=texastribune/walls-cache:buildcache
        cache-to: type=registry,ref=texastribune/walls-cache:buildcache,mode=max